apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-hunter-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: overly-permissive-role
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-hunter-sa-overly-permissive-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: overly-permissive-role
subjects:
- kind: ServiceAccount
  name: kube-hunter-sa
  namespace: default
